rlip_intereststree_controller_tree:
    path: /intereststree/tree
    defaults: { _controller: rlip.intereststree.controller:tree }
rlip_intereststree_controller_setrate:
    path: /intereststree/setRate
    defaults: { _controller: rlip.intereststree.controller:setRate }
rlip_intereststree_controller_addproposal:
    path: /intereststree/addProposal
    defaults: { _controller: rlip.intereststree.controller:addProposal }
rlip_intereststree_controller_getproposalcontainer:
    path: /intereststree/getProposalContainer
    defaults: { _controller: rlip.intereststree.controller:getProposalContainer }
rlip_intereststree_controller_proposalvote:
rlip_intereststree_controller_getusercontainer:
    path: /intereststree/getUserContainer
    defaults: { _controller: rlip.intereststree.controller:getUserContainer }
rlip_intereststree_controller_proposalvote:
    path: /intereststree/proposalVote
    defaults: { _controller: rlip.intereststree.controller:proposalVote }
rlip_intereststree_controller_proposalmanage:
    path: /intereststree/proposalManage
    defaults: { _controller: rlip.intereststree.controller:proposalManage }
rlip_intereststree_controller_treemanage:
    path: /intereststree/proposalManage
    defaults: { _controller: rlip.intereststree.controller:treeManage }
