services:
    rlip.intereststree.controller:
        class: rlip\intereststree\controller\main
        arguments:
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - @notification_manager
    rlip.intereststree.listener:
        class: rlip\intereststree\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
    rlip.intereststree.notification.type.inttree_proposal_accepted:
        class: rlip\intereststree\notification\inttree_proposal_accepted
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }
    rlip.intereststree.notification.type.inttree_proposal_rejected:
        class: rlip\intereststree\notification\inttree_proposal_rejected
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }